# Navigation Links
#   To link a homepage "widget" (within the same page), specify the URL as a hash `#` followed by the filename of the desired widget in your `/content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
#   To link a homepage "link" (different page), specify the URL as a /'folder'/

# [[main]]
#  name = "Publications"
#  url = "#publications"
#  weight = 20

[[main]]
    name = "Working papers"
    url = "#working-papers"
    weight = 10

[[main]]
    name = "Teaching"
    url = "#teaching"
    weight = 20

[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 30

# [[main]]
#  name = "test"
#  url = "/test/"
#  weight = 40

# [[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
